#!/usr/bin/env zsh
# Does the Python core say the same thing as the zsh it replaces?
#
# This is the project's own second-derivation rule applied to itself: two
# independent implementations, and the number only ships when they agree. Run it
# daily during the switchover; the zsh only retires after a clean week.
#
#   zsh core/parity.sh          today
#   zsh core/parity.sh -v       show the actual differences
#
# The digest is compared on its OUTPUT, not its file, because both write to the
# same path and the second would overwrite the first. Each runs against its own
# FIVE so neither can see the other's work.
set -uo pipefail
HERE="${0:A:h}"
REPO="${HERE:h}"
V="${1:-}"
tmp=$(mktemp -d) || exit 1
trap 'rm -rf "$tmp"' EXIT

fails=0
mkdir -p "$tmp/zsh" "$tmp/py" "$tmp/logs-zsh" "$tmp/logs-py"
sed 's|^LOGDIR=.*|LOGDIR='"$tmp"'/logs-zsh|' "$HOME/.beatbar/paths.conf" > "$tmp/conf-zsh"
sed 's|^LOGDIR=.*|LOGDIR='"$tmp"'/logs-py|'  "$HOME/.beatbar/paths.conf" > "$tmp/conf-py"

cmp_out() { # name, zsh file, py file
  if diff -q "$2" "$3" >/dev/null 2>&1; then
    print -r -- "  same    $1"
  else
    print -r -- "  DIFFERS $1  ($(diff "$2" "$3" | grep -c '^[<>]') lines)"
    fails=$((fails + 1))
    [[ "$V" == "-v" ]] && diff "$2" "$3" | head -40
  fi
}

print -r -- "parity, $(date '+%F %H:%M')"

# --- digest: the SESSIONS count and the body of the file each one writes
BEAT_CONF="$tmp/conf-zsh" FIVE="$tmp/zsh" BEAT_HOME="$REPO" \
  zsh "$REPO/digest.sh" > "$tmp/d.zsh.out" 2>"$tmp/d.zsh.err"
BEAT_CONF="$tmp/conf-py"  FIVE="$tmp/py"  BEAT_HOME="$REPO" \
  python3 "$HERE/scroll.py" digest > "$tmp/d.py.out" 2>"$tmp/d.py.err"
grep -h '^SESSIONS|' "$tmp/d.zsh.out" > "$tmp/s.zsh"
grep -h '^SESSIONS|' "$tmp/d.py.out"  > "$tmp/s.py"
cmp_out "digest SESSIONS|N" "$tmp/s.zsh" "$tmp/s.py"

# The generated-at line carries a clock and the trailing credit names the
# script, so neither can match; everything else must.
strip() { grep -v '^Generated \|^Generated by Scrollback' "$1"; }
zf=$(ls "$tmp"/zsh/week_*/*-context.md 2>/dev/null | head -1)
pf=$(ls "$tmp"/py/week_*/*-context.md 2>/dev/null | head -1)
if [[ -n "$zf" && -n "$pf" ]]; then
  strip "$zf" > "$tmp/b.zsh"; strip "$pf" > "$tmp/b.py"
  cmp_out "digest body" "$tmp/b.zsh" "$tmp/b.py"
else
  print -r -- "  MISSING one of the context files"; fails=$((fails + 1))
fi

# --- chats, both modes. Sorted: the zsh walks folders in glob order and the
# Python in sorted order, and neither promises an order to its caller.
for mode in active all; do
  [[ $mode == all ]] && A=1 || A=
  # The HH:MM column is the transcript's mtime, and a chat you are typing in
  # right now moves between the two calls. Masked, or this reports a difference
  # every time the harness runs inside an open session.
  BEAT_ALL=$A BEAT_CONF="$tmp/conf-zsh" FIVE="$tmp/zsh" BEAT_HOME="$REPO" \
    zsh "$REPO/chats_list.sh" 2>/dev/null | awk -F'|' -v OFS='|' '{$4="--:--"; print}' | sort > "$tmp/c.zsh"
  BEAT_ALL=$A BEAT_CONF="$tmp/conf-py" FIVE="$tmp/py" BEAT_HOME="$REPO" \
    python3 "$HERE/scroll.py" chats 2>/dev/null | sed '/^$/d' | awk -F'|' -v OFS='|' '{$4="--:--"; print}' | sort > "$tmp/c.py"
  cmp_out "chats ($mode, $(wc -l < "$tmp/c.zsh" | tr -d ' ') rows)" "$tmp/c.zsh" "$tmp/c.py"
done

# --- projects and history
BEAT_CONF="$tmp/conf-zsh" FIVE="$tmp/zsh" BEAT_HOME="$REPO" \
  zsh "$REPO/projects_list.sh" 2>/dev/null | sort > "$tmp/p.zsh"
BEAT_CONF="$tmp/conf-py" FIVE="$tmp/py" BEAT_HOME="$REPO" \
  python3 "$HERE/scroll.py" projects 2>/dev/null | sed '/^$/d' | sort > "$tmp/p.py"
cmp_out "projects" "$tmp/p.zsh" "$tmp/p.py"

# History reads the REAL 5_15 folder on both sides: it is the one command that
# reports on days this run did not generate.
BEAT_HOME="$REPO" zsh "$REPO/history_data.sh" 7 2>/dev/null > "$tmp/h.zsh"
BEAT_HOME="$REPO" python3 "$HERE/scroll.py" history 7 2>/dev/null | sed '/^$/d' > "$tmp/h.py"
cmp_out "history 7d" "$tmp/h.zsh" "$tmp/h.py"

# --- status. The clock line and the size of today's file move between the two
# calls, so they are dropped; the verdict, the PROBLEM lines and CHANGED are
# the part the app acts on.
sclean() { grep -v '^Checked just now' "$1" | sed 's/([0-9.]*K*, /(SIZE, /'; }
# Status reads the REAL 5_15 folder on both sides, because its whole job is to
# judge real artifacts. Only LOGDIR is redirected, and seeded with a copy of the
# run log so the login and last-block checks still have something to read:
# chats_list.sh caches into LOGDIR, and the live app writes that cache from a
# different checkout, which otherwise leaks its count into this comparison.
mkdir -p "$tmp/logs-st"
cp "$HOME/.claude/logs/daily-auto.log" "$tmp/logs-st/" 2>/dev/null
sed 's|^LOGDIR=.*|LOGDIR='"$tmp"'/logs-st|' "$HOME/.beatbar/paths.conf" > "$tmp/conf-st"
BEAT_CONF="$tmp/conf-st" BEAT_HOME="$REPO" zsh "$REPO/scroll_status.sh" 2>/dev/null > "$tmp/st.zsh.raw"
rm -f "$tmp"/logs-st/.chats-*.cache
BEAT_CONF="$tmp/conf-st" BEAT_HOME="$REPO" python3 "$HERE/scroll.py" status 2>/dev/null > "$tmp/st.py.raw"
sclean "$tmp/st.zsh.raw" > "$tmp/st.zsh"; sclean "$tmp/st.py.raw" > "$tmp/st.py"
cmp_out "status (full)" "$tmp/st.zsh" "$tmp/st.py"
grep -E '^(5/15 collection|PROBLEM:|FIX\||CHANGED\|)' "$tmp/st.zsh.raw" > "$tmp/v.zsh"
grep -E '^(5/15 collection|PROBLEM:|FIX\||CHANGED\|)' "$tmp/st.py.raw"  > "$tmp/v.py"
cmp_out "status (verdict lines)" "$tmp/v.zsh" "$tmp/v.py"

print -r -- ""
if (( fails )); then
  print -r -- "$fails difference(s). Not ready to switch."
  [[ "$V" != "-v" ]] && print -r -- "Run with -v to see them."
else
  print -r -- "No differences."
fi
exit $(( fails ? 1 : 0 ))
